sudo: required
services:
- docker
language: python
python:
- '3.7'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install names
- pip install nose
- pip install Flask-Testing
- pip install Werkzeug

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag yixian7777777/swagger_server yixian7777777/swagger_server
- docker push yixian7777777/swagger_server
env:
  global:
  - secure: weIx95wGF1PeTXIP0OlaFuy/OMxdT9cQ5Vj5rj4MKvpfN7j1th2Jt7RLJ0AI+W4cMfJRn+7TRb71Nyu4JR8ljlB5cK+r7ttDqHUx6QHn5eOtqffLob/ojOWBubH40tnkHn+wFX6zPr21T05sjpeOe0vyGQbp/ea8HDOiuT3ci0RNGIbGNQ6y984VUsLKpxlwmYjfu9TdFkGPujk+mZMM8rKMAQ6E3vgfLNS9UBpaNsvHtm81ky/YLTtA/tQR8mPN6/I2v1bnnjgG9sMQe00S5dvTf6MwClTPESXh3fqx3CDfw9PGRfp037hZNTviMqV8sGmAPvtjKyyDRWER4a0jFf5rHJ9vwyOBLub3k/YF07QWLKLraZU1rARKUB/EffskxgkxbbGCTGqs+gIt6JlojPqCxMFti3e+ZRAEAaYfafHAFiap+4A5xdon+74FW2Cfhci1Wk2h2cvyAajbey8bNCCbFSJve8XGNfJsFxag2xUehs6QSKDnsEfpEG39ReqJCEjjs5JOATCKJphszWVnMgNml1YYBN9hCTwwVPIk13VSUdDhy9NyEvoFQfEgE9Lb7rVC87D8WGmUt4wJGwp9/JCItr0kJkavZq3VP0ZEsIEsM+X77GvM2Kr4HghDePIlYTYj4ptwO4GfMM+F7Sh7Hh1OhBdKp7zyK7KKlMsftuA=
  - secure: Xs2qZhR5yeRx5MzOh8nwaogWgZdf4ncdUtvHLTEnkeEp9lOAiS44vG7a3xabAzmKTgZ5Q+tdltKOqKnTJSGNZmP3XKzFOsA/SPC9CWLsompUhV5bEMSPrDOQRm9hrsQnG4YxcxeANuKbL8t1wzw2E++Jglve3pHR5MwYQ6lLDfPtVARXrqGssKAwY0eUKoJnZaSy1YWA4ZIu+7V0QN+DfLsYbAsWbTmUl7bEODwATpwFGJ0yRbGPN1ScDx77ZntmdwH6cxyT4yuuX/WGRbIoSw3iURaGlozKFp6aMdte3FL5wl8Z0w00kh+DwqTppIpWUj38JkTmCIabRPcMrtbTQBMisinFMAiEShfdD+hAhpslqFFKzvUX4m19G0v2xUxXyRjaAFa7XpYugMfVuw9XvaR/+8oavRecxAO6kLSwAOMA5xdLjRlQ7OOKTg29K5O0/ji6Qq/YLAl9sqwd8NlyBs7SrekiDkAdPRlLgJ1toya6gYTHR1rDpPwGZv5woUNdo6ADNYGIEaxP7y43Sz3HSvKsYqO854fYZp8rjjjmacWh05cz8PQo7VHV3TeCXK8u2BPREwijKnGTS5MM+w7BaziHTeNOV/N3Yw1xydkT/HduBPgtZcmzgKghars6sRMfMxnvWw7FpmXF5zJYpuuNfVIpV7hW2+tI3WNkAgcVbRk=
